import { Inter } from "next/font/google";
import "../../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import SimpleNavbar from "@/components/containers/simple-navbar";
import { auth } from "@/auth"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function ContaduriaLayout({ children }) {
  
  const session = await auth()
  
  if (session?.user?.role !== "contaduria") {
   return <div>No eres del area de Contduria</div>
  }

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <SimpleNavbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}